### ISSUE TITLE
Amazon search links broken

### ISSUE THREAD

**Issue by paul1149** [dividedby/General-URL-Cleaner-Revived#15]
Great script, but it seems to be breaking search links at amazon.com. I get "page not found" error clicking on a search hit. When I disable the script, the links work.

How would I exclude Amazon, and ideally not have that overwritten on the next update?

I'm on 4.2.5

Thanks.

**Comment by dividedby** [comment]
Hello, what browser are you using and are you using any other extensions that touch Amazon? I use the script everyday in Firefox desktop and Safari on mobile and don’t have that issue. If we could figure out what’s going on that would be great.

Otherwise if you change this @include in this line to @exclude:
// @include     /^https:\/\/[a-z0-9.]*\.?amazon(\.[a-z0-9]{2,3})?(\.[a-z]+)?\/.*$/

Then it will just exclude Amazon links. Or you could delete the line. I don’t know of anyway to prevent it from being overwritten when the script updates though.

**Comment by paul1149** [comment]
Hi. I'm in Vivaldi desktop. The only extension that I could see affecting this is Stylus, for applying local css style sheets. But it never caused this problem before, and still doesn't when I turn off Violent Monkey.

I will keep your answer for future reference, but for now I went into Violent Monkey's global settings and made an @exclude rule:

`@exclude-match *://www.amazon.com/*`

Since I did this the problem disappeared. 

This will not be affected by script updates. If I ever install a script for amazon, though, I will have to revert to your script-level solution.

Thanks much. I guess I'll close this issue. Be well.
